apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: ingress-input-service
  namespace: calculator
spec:
  rules:
  - host: {{ .Values.inputServiceHost }}
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name:  input-service
            port: 
              number: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: ingress-output-service
  namespace: calculator
spec:
  rules:
  - host: {{ .Values.outputServiceHost }}
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name:  output-service
            port: 
              number: 9001

