apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: ingress-output-service
  namespace: calculator
spec:
  rules:
  - host: demo-output-service
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name:  output-service
            port: 
              number: 9001
